export const GET_DEVICES = 'GET_DEVICES'
export const LOAD_DEVICES = 'LOAD_DEVICES'

export const SEARCH_CHANGE = 'SEARCH_CHANGE'

export const GET_SUGGESTIONS = 'GET_SUGGESTIONS'
export const LOAD_SUGGESTIONS = 'LOAD_SUGGESTIONS'
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS'

export const GET_DETAILS = 'GET_DETAILS'
export const LOAD_DETAILS = 'LOAD_DETAILS'

export const GET_POPULAR_DEVICES = 'GET_POPULAR_DEVICES'
export const LOAD_POPULAR_DEVICES = 'LOAD_POPULAR_DEVICES'

export const UPDATE_VIEWS = 'UPDATE_VIEWS'

export const SET_LOADING = 'SET_LOADING'
export const RESET_LOADING = 'RESET_LOADING'
