# Generated by Django 3.2.8 on 2021-10-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacter', models.CharField(max_length=100)),
                ('ram_amount', models.IntegerField()),
                ('processor_manufacturer', models.CharField(choices=[('AMD', 'AMD'), ('Intel', 'Intel')], max_length=10)),
                ('processor_frequence', models.CharField(max_length=100)),
                ('processor_cores_number', models.IntegerField()),
                ('display_resolution', models.CharField(max_length=100)),
                ('display_diagonal_size', models.CharField(max_length=5)),
                ('storage_capacity', models.CharField(max_length=100)),
                ('graphics_card_type', models.CharField(max_length=100)),
                ('graphics_card_model', models.CharField(max_length=100)),
                ('operating_system', models.CharField(choices=[('Windows 10', 'Windows 10'), ('FreeDOS', 'FreeDOS'), ('MacOS', 'MacOS')], max_length=100)),
                ('img', models.ImageField(default='default.jpg', upload_to='uploads/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
