# Generated by Django 3.2.8 on 2021-10-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='manufacter',
            new_name='manufacturer',
        ),
    ]
