# Generated by Django 3.2.8 on 2021-10-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_manufacter_laptop_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='laptop',
            name='starting_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='display_resolution',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='graphics_card_model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='graphics_card_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(choices=[('Windows 10', 'Windows 10'), ('FreeDOS', 'FreeDOS'), ('MacOS', 'MacOS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor_frequence',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_capacity',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
