# Generated by Django 3.2.8 on 2021-10-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_mouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
    ]
