# Generated by Django 3.2.8 on 2021-10-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_mouse_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('starting_price', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('display_type', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('response_time', models.IntegerField()),
                ('curved_screen', models.CharField(max_length=3)),
                ('img', models.ImageField(default='default.jpg', upload_to='uploads/')),
            ],
        ),
    ]
