# Generated by Django 3.2.8 on 2021-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='darwin_link',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='darwin_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptop',
            name='enter_link',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='enter_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitor',
            name='darwin_link',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='monitor',
            name='darwin_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitor',
            name='enter_link',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='monitor',
            name='enter_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouse',
            name='darwin_link',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='mouse',
            name='darwin_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouse',
            name='enter_link',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='mouse',
            name='enter_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='starting_price',
            field=models.IntegerField(),
        ),
    ]
