# Generated by Django 3.2.8 on 2021-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20211015_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='darwin_link',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='enter_link',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='darwin_link',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='enter_link',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='darwin_link',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='enter_link',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
