# Generated by Django 3.2.8 on 2021-10-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_darwinproducts_enterproducts_laptopcategory_monitorcategory_mousecategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darwinproducts',
            name='link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enterproducts',
            name='link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=50),
        ),
    ]
