# Generated by Django 3.2.8 on 2021-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20211019_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darwinproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='enterproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='darwinproducts',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterproducts',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopcategory',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitorcategory',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mousecategory',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
